services:
    main:
        container_name: jury-main
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - MAILGUN_API_KEY=${MAILGUN_API_KEY}
            - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
            - MAILGUN_IS_EU_TRUE_FALSE=${MAILGUN_IS_EU_TRUE_FALSE}
            - VITE_JURY_NAME=${JURY_NAME}
            - PORT=8000
        build:
            context: './'
            dockerfile: Dockerfile
            args:
                - VITE_JURY_NAME=${JURY_NAME}
                - VITE_JURY_URL=/api
                - VITE_HUB=${HEHE:-}
        ports:
            - ${PORT:-8000}:8000
