services:
    mongo:
        build:
            context: './'
            dockerfile: mongo.Dockerfile
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
            - MONGO_INITDB_DATABASE=jury
            - MONGO_REPLICA_SET_NAME=rs0
        ports:
            - 27017:27017
        volumes:
            - './data:/data/db'
        networks:
            - jury-dev-network

    mongorssetup:
        depends_on:
            - 'mongo'
        image: mongo:latest
        environment:
            - MONGODB_USER=${MONGODB_USER}
            - MONGODB_PASS=${MONGODB_PASS}
        volumes:
            - .:/scripts
        restart: "no"
        entrypoint: [ 'bash', '/scripts/init-mongo-rs.sh' ]
        networks:
            - jury-dev-network

    go-dev:
        depends_on:
            - 'mongo'
            - 'mongorssetup'
        container_name: jury-dev-backend
        environment:
            - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/
            - JURY_ADMIN_PASSWORD=${JURY_ADMIN_PASSWORD}
            - EMAIL_HOST=${EMAIL_HOST}
            - EMAIL_PORT=${EMAIL_PORT}
            - EMAIL_FROM=${EMAIL_FROM}
            - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
            - MAILGUN_API_KEY=${MAILGUN_API_KEY}
            - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
            - MAILGUN_IS_EU_TRUE_FALSE=${MAILGUN_IS_EU_TRUE_FALSE}
            - VITE_JURY_NAME=${JURY_NAME}
            - PORT=8000
        build:
            context: './'
            dockerfile: dev.Dockerfile
        ports:
            - ${PORT:-8000}:8000
        volumes:
            - ./server:/jury
        networks:
            - jury-dev-network

    node-dev:
        depends_on:
            - 'go-dev'
        container_name: jury-dev-frontend
        environment:
            - VITE_JURY_NAME=${JURY_NAME}
            - VITE_JURY_URL=http://localhost:${PORT:-8000}/api
            - VITE_HUB=${HEHE:-}
        build:
            context: './'
            dockerfile: client/dev.Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./client:/client
        networks:
            - jury-dev-network

networks:
    jury-dev-network:
        driver: bridge
